services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.deploy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./shared:/usr/src/shared
      - ./backend:/usr/src/app
    image: dc4653/code-stage:latest

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./shared:/usr/src/shared
      - ./frontend:/usr/src/app
