export interface Review {
    id: number;
    content: string;
    filePath: string;
    lineNumber: number;
    fkGithubRepositoryId: number;
    createdAt: Date;
}

export const dummyReviews: Array<Review> = [
    {
        id: 0,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 1,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 2,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 3,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 4,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 5,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 6,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 7,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 8,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 9,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 10,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 11,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 12,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 13,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 14,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 15,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 16,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 17,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 18,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 19,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 20,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 21,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 22,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 23,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 24,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 25,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
    {
        id: 26,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        fkGithubRepositoryId: 10,
        createdAt: new Date(),
    },
]