import ReviewResponseDto from "shared/dist/review/dto/review.response.dto";

export const dummyReviews: Array<ReviewResponseDto> = [
    {
        reviewId: 0,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 1,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 2,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 3,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 4,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 5,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 6,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 7,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 8,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 9,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 10,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 11,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 12,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 13,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 14,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 15,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 16,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 17,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 18,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 19,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 20,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 21,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 22,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 23,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 24,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 25,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
    {
        reviewId: 26,
        content: '이 코드는 정말이지 놀랍다. 세계 수준의 우수성',
        filePath: '',
        lineNumber: 10,
        repositoryId: 10,
        createdAt: new Date(),
    },
]